### ISSUE TITLE
add cider-like shortcuts

### ISSUE THREAD

**Issue by a13** [xiongtx/eros#4]
As a person, who codes mostly in Clojure, I've got used to Cider commands bindings (well, some of them) and miss them very much when I code in Emacs lisp.

The thing is there are not so many elisp counterparts to keep them in a separate package (though I thought about this), but enough not to keep them in init.el.

So, do you think it's a good idea to add another minor mode with a cider-like keymap to EROS?

**Comment by xiongtx** [comment]
What shortcuts do you envision? All there is to do is turn the mode on.

**Comment by a13** [comment]
e.g. these
https://github.com/clojure-emacs/cider/blob/a6bd328fc8d9201de3a8272ae05e7015c5f75e7b/cider-doc.el#L60

It would be great to have some kind of (disabled by default, of course) eros-cider-minor-mode enabling keymap with `C-c C-d d` as `describe-symbol`, `C-c C-d a` as `M-x apropos-documentation` and so on

**Comment by xiongtx** [comment]
Sorry, that's out of the scope of this package--all this package does is create an inline evaluation result overlay.
