### ISSUE TITLE
Inline results of edebug steps

### ISSUE THREAD

**Issue by nikolavojicic** [xiongtx/eros#9]
It would be nice to display the results of **edebug** steps inline, the same way they are displayed in CIDER.

**Comment by nikolavojicic** [comment]
Easy way is via advices...

```elisp
(advice-add 'edebug-safe-prin1-to-string
            :before
            (lambda (value)
              (eros--eval-overlay
               value
               edebug-point)))
```

This works but it's probably [not idiomatic](https://www.emacswiki.org/emacs/AdviceVsHooks).  

EDIT: it doesn't work if debugger jumps into another buffer.

**Comment by codeasone** [comment]
See also: https://xenodium.com/inline-previous-result-and-why-you-should-edebug/ 

The advices in this post seems to work seamlessly, incl. across multiple buffers where multiple `defun`'s are instrumented e.g.
